# This is a basic workflow that is manually triggered

name: Build Native Image and deploy it to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      id: checkout
      with:
        java-version: '21'      # See 'Options' for more details
        distribution: 'graalvm' # See 'Supported distributions' for available options
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Native Image
      id: build
      if: steps.checkout.outcome == 'success'
      run: |
        mvn -Pnative package

    - name: packaging
      id: packaging
      run: |
        pwd
        cd target/${{ secrets.AZURE_FUNCTIONS_APP_NAME }}
        zip -r -0 ../${{ secrets.AZURE_FUNCTIONS_APP_NAME }}-0.1.zip .
        
    # - name: 'Deploy to Azure Function'
    #   uses: Azure/functions-action@v1
    #   with:
    #     app-name: ${{ secrets.AZ_FUNCTION_NAME_APP }}
    #     package: target/native_spring_function.zip

    - name: push artifact
      uses: actions/upload-artifact@v4
      if: steps.packaging.outcome == 'success'
      with:
        name: my-artifact
        path: target/${{ secrets.AZURE_FUNCTIONS_APP_NAME }}.zip
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: login Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: pop artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: ./

    - name: Display structure of downloaded files
      run: |
        ls -R ./
        unzip -t ${{ secrets.AZURE_FUNCTIONS_APP_NAME }}.zip
        
